import { SourceSans } from "@/ui/fonts";
import "@/ui/globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="pt-br">
      <body className={SourceSans.className}>{children}</body>
    </html>
  );
}
