import { SourceSans } from "@/app/ui/fonts";
import "@/app/ui/globals.css";
import TopBar from "@/app/ui/top-bar";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v14-appRouter";
import { Providers } from "./providers";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={SourceSans.className}>
        <AppRouterCacheProvider>
          <Providers>
            <TopBar />
            {children}
          </Providers>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
